### PR TITLE
stop claiming watchOS support

### PR DESCRIPTION
**Pull request by dduan**
The project doesn't compile for watchOS.

### CODE REVIEW

**Comment by Reflejo** [comment]
can we make it compile on watchOS instead? Or what's preventing this to work on watchos

**Comment by dduan** [comment]
CFNetwork is not available in watchOS.

**Comment by Reflejo** [comment]
It should be on watchOS 2.0+?

**Comment by dduan** [comment]
The documentation doesn't seem to to match the reality.

Daniel Duan

**Comment by Reflejo** [comment]
+1 k

**Pull request merged**
