### PR TITLE
Allow callers to set an initial offset to be used while `sync` occurs.

### PR DESCRIPTION
**Pull request by mallorypaine**

### CODE REVIEW

**Comment by goaway** [comment]
looks good to me.

minor nit - I'd consider still having `from`/`pool` be the first argument.

**Comment by Reflejo** [comment]
Thanks for the PR; the offset is not enough to guarantee a trustful time so Kronos will report an invalid time unequivocally after every every reboot.

I think we should go ahead and implement caching here so we can prevent this problem by caching last uptime as well and compare with the current one while restoring the cache (and no-op if the uptime drifted)

Some people also [expressed interest](https://github.com/lyft/Kronos/issues/15) about this before so would be nice to have it here, instead of leaving it up to the consumer.

**Comment by mallorypaine** [comment]
Any thoughts on caching mechanism? Maybe something like writing a dictionary file to `~/Library/Caches` and adding `TimeFreeze.toDictionary()` and `TimeFreeze(dictionary:)`?

**Comment by Reflejo** [comment]
Yea or `UserDefaults`. No preference here

**Comment by mallorypaine** [comment]
Closing. Will open a new PR that includes the self-contained caching.

**Comment by mallorypaine** [comment]
New PR here: https://github.com/lyft/Kronos/pull/22

**Pull request closed without merging**
