### PR TITLE
Update xcode version checks. Recommended compiler warnings on.

### PR DESCRIPTION
**Pull request by gmorning**

### CODE REVIEW

**Comment by Reflejo** [comment]
Can you just modify `LastUpgradeCheck` ? That should be enough, no?

**Comment by gmorning** [comment]
Yes I can, but why not making code safer at a very low cost?
Theese changes were made automatically by Xcode 9.1, they are defaults if you start a new project.

**Comment by Reflejo** [comment]
I don’t see how adding a bunch of clang flags which are defaults anyway could make any code safer on a full swift project but it won’t make any harm so I’m ok merging this.

... but before I do that could you please sing the CLA? please follow the steps from https://github.com/lyft/Kronos/blob/master/CONTRIBUTING.md

**Comment by gmorning** [comment]
Done. Check is still red, but when I press `details` I see `Signed and current (1.0)`

**Comment by henrymly** [comment]
@gmorning I ran it to the same issue because my `git config user.email` was different than my GitHub email address used to sign the CLA. Try syncing those up and see if that works for you!

**Pull request merged**
